/** The details of errors generated by Google API servers. */
export interface GoogleApiErrorDetails {
  /** The resource name or URL of the protocol buffer message. */
  readonly "@type": string;
  /** The additional details about the error. */
  readonly [property: string]: unknown;
}

/** The payload of errors generated by Google API servers. */
export interface GoogleApiErrorPayload {
  /** An HTTP status code corresponding to the error's gRPC status code. */
  readonly code: number;
  /** A human-readable description of the error. */
  readonly message: string;
  /** The gRPC status code of the error. */
  readonly status?: string;
  /** An array of objects containing additional details about the error. */
  readonly details?: readonly GoogleApiErrorDetails[];
}

/** The JSON body of a Google API's error response. */
export interface GoogleApiErrorResponseBody {
  /** The error's actual payload. */
  readonly error: GoogleApiErrorPayload;
}

/** An error generated by Google API servers. */
export class GoogleApiError extends Error implements GoogleApiErrorPayload {
  /** A human-readable description of this error. */
  declare readonly message;

  /** An HTTP status code corresponding to this error's gRPC status code. */
  readonly code;
  /** The gRPC status code of this error. */
  readonly status?;
  /** An array of objects containing additional details about this error. */
  readonly details?;

  /**
   * Constructs a new Google API error object using the passed payload.
   * @param payload The error's payload.
   */
  constructor(payload: Readonly<GoogleApiErrorPayload>) {
    super(payload.message);

    this.name = "GoogleApiError";
    this.code = payload.code;
    this.status = payload.status;
    this.details = payload.details;
  }
}
